/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpeseQuotidianeRouteImport } from './routes/spese-quotidiane'
import { Route as PianoRouteImport } from './routes/piano'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DebitiCreditiRouteImport } from './routes/debiti-crediti'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BolletteRouteImport } from './routes/bollette'
import { Route as AbbonamentiRouteImport } from './routes/abbonamenti'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SpeseQuotidianeRoute = SpeseQuotidianeRouteImport.update({
  id: '/spese-quotidiane',
  path: '/spese-quotidiane',
  getParentRoute: () => rootRouteImport,
} as any)
const PianoRoute = PianoRouteImport.update({
  id: '/piano',
  path: '/piano',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DebitiCreditiRoute = DebitiCreditiRouteImport.update({
  id: '/debiti-crediti',
  path: '/debiti-crediti',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BolletteRoute = BolletteRouteImport.update({
  id: '/bollette',
  path: '/bollette',
  getParentRoute: () => rootRouteImport,
} as any)
const AbbonamentiRoute = AbbonamentiRouteImport.update({
  id: '/abbonamenti',
  path: '/abbonamenti',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abbonamenti': typeof AbbonamentiRoute
  '/bollette': typeof BolletteRoute
  '/coach': typeof CoachRoute
  '/debiti-crediti': typeof DebitiCreditiRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/spese-quotidiane': typeof SpeseQuotidianeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abbonamenti': typeof AbbonamentiRoute
  '/bollette': typeof BolletteRoute
  '/coach': typeof CoachRoute
  '/debiti-crediti': typeof DebitiCreditiRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/spese-quotidiane': typeof SpeseQuotidianeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abbonamenti': typeof AbbonamentiRoute
  '/bollette': typeof BolletteRoute
  '/coach': typeof CoachRoute
  '/debiti-crediti': typeof DebitiCreditiRoute
  '/login': typeof LoginRoute
  '/piano': typeof PianoRoute
  '/spese-quotidiane': typeof SpeseQuotidianeRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abbonamenti'
    | '/bollette'
    | '/coach'
    | '/debiti-crediti'
    | '/login'
    | '/piano'
    | '/spese-quotidiane'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abbonamenti'
    | '/bollette'
    | '/coach'
    | '/debiti-crediti'
    | '/login'
    | '/piano'
    | '/spese-quotidiane'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/abbonamenti'
    | '/bollette'
    | '/coach'
    | '/debiti-crediti'
    | '/login'
    | '/piano'
    | '/spese-quotidiane'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbbonamentiRoute: typeof AbbonamentiRoute
  BolletteRoute: typeof BolletteRoute
  CoachRoute: typeof CoachRoute
  DebitiCreditiRoute: typeof DebitiCreditiRoute
  LoginRoute: typeof LoginRoute
  PianoRoute: typeof PianoRoute
  SpeseQuotidianeRoute: typeof SpeseQuotidianeRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spese-quotidiane': {
      id: '/spese-quotidiane'
      path: '/spese-quotidiane'
      fullPath: '/spese-quotidiane'
      preLoaderRoute: typeof SpeseQuotidianeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/piano': {
      id: '/piano'
      path: '/piano'
      fullPath: '/piano'
      preLoaderRoute: typeof PianoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debiti-crediti': {
      id: '/debiti-crediti'
      path: '/debiti-crediti'
      fullPath: '/debiti-crediti'
      preLoaderRoute: typeof DebitiCreditiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bollette': {
      id: '/bollette'
      path: '/bollette'
      fullPath: '/bollette'
      preLoaderRoute: typeof BolletteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abbonamenti': {
      id: '/abbonamenti'
      path: '/abbonamenti'
      fullPath: '/abbonamenti'
      preLoaderRoute: typeof AbbonamentiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbbonamentiRoute: AbbonamentiRoute,
  BolletteRoute: BolletteRoute,
  CoachRoute: CoachRoute,
  DebitiCreditiRoute: DebitiCreditiRoute,
  LoginRoute: LoginRoute,
  PianoRoute: PianoRoute,
  SpeseQuotidianeRoute: SpeseQuotidianeRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
